### PR TITLE
feat: [proposal] allow to customize service method for each controller's route

### PR DESCRIPTION
**Pull request by nhatphongdo**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Documentation content changes
-   [ ] Other... Please describe:

## What is the current behavior?

For now, controller routes will execute the pre-defined logic in the service class. But sometimes, we may need to customize the behavior of logic which cannot be done with interceptors.

## What is the new behavior?

Allow to set up the `serviceMethod` for each route. This field indicates the name of the method that will be executed inside the corresponding controller's route.
If `serviceMethod` is not defined or identifies a wrong method, the existing built-in method will be used instead, just like the current behavior.

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by jiho-kr** [comment]
Great to see you again @nhatphongdo 

I understood your intentions to `override at the service level` from this MR.

I created an `Override Decorator` assuming a `similar situation`, and I expected to customize the Interceptor and Service by `override at the controller level` instead of understanding all 'Interceptor - Controller - Service - Interceptor'.

I learned that  high understanding of the library may want to override the service only. (Like this MR)

<hr/>

The steps to call the service from the `controller after the interceptor` are as follows
```
# crud.route.factory
    ...
    protected readOne<T>(controllerMethodName: string) {
        this.targetPrototype[controllerMethodName] = function reservedReadOne(crudReadOneRequest: CrudReadOneRequest<T>) {
            return this.crudService.reservedReadOne(crudReadOneRequest);
        };
    }
    
    protected readMany<T>(controllerMethodName: string) {
    ... others Service Method
```

I think that the  `Goal of this MR` can be achieved if the `Override Decorator` is currently providing it at the `controller` level, and this function can be extended by the `service` level.

**Comment by nhatphongdo** [comment]
Hi @jiho-kr,

Thanks for your detailed comment. Actually, I tried all possible ways I understand from lib before approaching this way.

Let me explain my use case before sharing my solutions. Please guide me if the current logic can solve the problem.
* Basically, my use case is similar to `CreateRequestInterceptor`. I need to insert some data (like `author`) automatically into the entity but still keep all other logic such as validation.
* My entity is like this:
```
export class RevisionsEntity extends AbstractEntity {
    @PrimaryGeneratedColumn()
    @Type(() => Number)
    @IsNumber(undefined, { groups: [GROUP.PARAMS, GROUP.SEARCH] })
    @Min(1, { groups: [GROUP.SEARCH] })
    @IsOptional({ groups: [GROUP.SEARCH] })
    id: number;

    @Column({ type: 'integer' })
    @IsNumber(undefined, { groups: [GROUP.SEARCH] })
    @Min(1, { groups: [GROUP.SEARCH] })
    @IsOptional({ groups: [GROUP.SEARCH] })
    revision: number;

   ...
}
```
* I need to increase `revision` by 1 automatically for the new entity.

Here are my tries so far:
1. Use interceptor
```
export class GenerateRevisionNumberInterceptor implements NestInterceptor {
    constructor(public readonly crudService: RevisionsService) {}

    async intercept(context: ExecutionContext, next: CallHandler): Promise<Observable<any>> {
        const req: Record<string, any> = context.switchToHttp().getRequest<Request>();

        const count = await this.crudService.repository.count();
        if (req.body) {
            req.body.revision = count + 1;
        }

        return next.handle();
    }
}
```
Problems:
* This interceptor is executed **before** the standard interceptor, in this case, `CreateRequestInterceptor`. So validation logic will throw an error because we don't allow to input `revision` in CREATE method.
```
Reflect.defineMetadata(
    INTERCEPTORS_METADATA,
    [
        ...(this.crudOptions.routes?.[crudMethod]?.interceptors ?? []),
        isOverride ? undefined : CRUD_POLICY[crudMethod].interceptor(this.crudOptions, factoryOption),
    ].filter(Boolean),
    targetMethod,
);
```
2. Use `Override` decorator
```
    @Override('CREATE')
    @UseInterceptors(GenerateRevisionNumberInterceptor)
    async create(@Body(new ValidationPipe({ forbidNonWhitelisted: true, groups: [GROUP.CREATE] })) crudCreateRequest: TermRevisionsEntity) {
        this.crudService.reservedCreate({
            body: crudCreateRequest,
            author: {
                property: 'createdBy',
                filter: 'user',
            }
        })
    }

```
Problems:
* Because overridden controller's method cannot reuse standard interceptor, we cannot utilize `CreateRequestInterceptor`. Instead, we need to do validation manually or replicate the logic of `CreateRequestInterceptor`. Both are not efficient, I think.
* The same for parameter will be passed to service if we want to reuse standard service's method.
* CRUD factory class will use configuration from `CrudOptions` to setup the controller's method. While our custom controller method is separated. It can lead to some conflict or misunderstanding. For example, I used `@ApiOperation` to setup Swagger summary for custom controller method, but it won't take effect because CRUD factor will override it by value from `swagger` in `CrudOptions`. So I need to use `decorators` in `CrudOptions` along with decorator in custom method like below. It's not convenient.
```
@Crud({
    entity: RevisionsEntity,
    only: [Method.CREATE],
    routes: {
        create: {
            decorators: [
                ApiOperation({
                    summary: 'Create new Revision',
                }),
            ]
        }
   }
})
...
    @Override('CREATE')
    @UseInterceptors(GenerateRevisionNumberInterceptor)
    <Other decorators if needed>
    async create(@Body(new ValidationPipe({ forbidNonWhitelisted: true, groups: [GROUP.CREATE] })) crudCreateRequest: TermRevisionsEntity) {
    ...
    }

```

That's why I come to this proposal. This MR aims to provide the customization for the use-case that we want to keep all standard logic of controller and request process flow.

Thanks.

**Comment by jiho-kr** [comment]
As I understand it, `Modify the revision value when the API call is success.'

I'm guessing that in this case, it could be handled through an interceptor after the request is processed, like this

```
@Injectable()
export class ChangedRevisionInterceptor extends CustomRequestInterceptor {
    constructor(private readonly invoiceGroupService: InvoiceGroupService) {
        super();
    }

    async intercept(_context: ExecutionContext, next: CallHandler): Promise<Observable<unknown>> {
        return next.handle().pipe(
            map(async (userEntity: UserEntity): Promise<UserEntity> => {
                // TODO: update revision (Interceptor -> controller -> service -> [Here] Interceptor)
                // This is called after the service(CRUD Service) has completed.
                await this.revisionsService.update(userEntity);
                
                return userEntity;
            }),
        );
    }
}
```

If it needs to be protected by a transaction or processed in a single DB call, it would have to be handled differently.

**Comment by nhatphongdo** [comment]
@jiho-kr 
Yes, you are right. It would be handled in a transaction. To simplify the sample, I used `count`. But realistically, we need to find the latest revision, plus 1 to it, and store to DB in 1 transaction. Besides that, `revision` is a required column. If we do in response interceptor, we need to set it to `nullable` or a dump value like `-1` or `0`. It may have some side-effect in handling logic in other places.

**Comment by jiho-kr** [comment]
It seems like you're expecting it to behave like a DB trigger. 
I think it would be better to handle this case as a method of a separate service rather than an override.

I'm struggling with how to provide `like hooking` without adding complexity.

**Comment by jiho-kr** [comment]
Hi @nhatphongdo 

I realized that there is a `simple way` to accomplish your goal.

It doesn't involve modifying the library, but rather `overriding the method(starts with reserve) in the service`. 

However, I think it is better to `create a new method than Override` because CrudService contains the main functions of the library.

It can refer to `CrudService` (lib/curd.service.ts).

After you check this comment, you will be able to close the MR.

**Comment by nhatphongdo** [comment]
Hi @jiho-kr,

You're right! Overriding the method can help me. I need to replicate a few lines of code (to set the `author`) but it's still better than using `Override` decorator in controller, clone some behaviors in `CrudController` like validation, and execute a custom service function. I will follow this approach first. Then I will try to figure out the better way to handle this situation and make other proposal to the library if possible.

For now, I will close this request as it's invalid. Thank you so much again for your comments.

**Pull request closed without merging**
